[build]
  # Directory to change to before starting a build
  base = "."
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist/numerino-student-web-app"
  # A build command to execute before deploying
  command = "npm install && ng build --configuration production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Set Node.js version
  NODE_VERSION = "18" 